default_mode: multiple_notes
tmp_root: /tmp/
oauth_callback: https://evernotebot.djud.me/evernote/oauth
storage:
    users:
        class: evernotebot.bot.storage.Sqlite
        dirpath: /tmp/evernotebot-data/
        db_name: evernotebot
        collection: users
    failed_updates:
        class: evernotebot.bot.storage.Sqlite
        dirpath: /tmp/evernotebot-data/
        db_name: evernotebot
        collection: failed_updates
